### ISSUE TITLE
Learning Catalogue Eurostat entries image missing

### ISSUE THREAD

**Issue by ChallenerSJ** [SDMX-Outreach/sdmx-learning-catalogue#22] opened 2024-03-21 13:57 UTC
Hello, @OSoerensen @fernandohandball,
It seems the links to the featured image are broken again. Can you check and update and also why they keep changing?

![image](https://github.com/SDMX-Outreach/sdmx-learning-catalogue/assets/16560105/66f28550-f413-48ae-8630-324345ab03c9)

**Comment by fernandohandball** [comment] 2024-03-21 14:09
Hello @ChallenerSJ ,

Thanks for alerting us. Unfortunately our communication and training portal, where the images are stored, is down since this morning. The corresponding team has been informed but I don't have a clear timeline when the page will be up again.

Let's leave the issue open and I'll come back to you as soon as I have more details.

**Comment by OSoerensen** [comment] 2024-03-28 07:28
Checked this morning, and the server with the images seems still to be down. We keep the issue open.

**Comment by OSoerensen** [comment] 2024-04-03 15:18
Hello @fernandohandball is the server still down, the images is still not visible?

**Comment by fernandohandball** [comment] 2024-04-09 09:29
Hello @ChallenerSJ and @OSoerensen,

The page is up but the logos are not being displayed. While we try to find the cause of such behaviour, I have uploaded the logos and created new URLs. However I am not sure whether uploading the 'catalogue.json' file is what I should do. Here are the new URLs

https://cros.ec.europa.eu/system/files/2024-02/SDMX%20Converter%20Training%20logo.png

https://cros.ec.europa.eu/system/files/2024-02/Euro-SDMX%20Registry%20training%20logo.png

https://cros.ec.europa.eu/system/files/2024-02/ESTP%20icon.png 
 
Best,
Fernando

**Comment by ChallenerSJ** [comment] 2024-04-09 13:25
Hello @fernandohandball, in fact you have to branch and update the .json file and then submit a pull request for review and merging.

**Comment by fernandohandball** [comment] 2024-04-09 13:34
@ChallenerSJ thanks for sharing the process details. I am not sure if I have done it right but you should receive a review request in addition to Ole...

https://github.com/SDMX-Outreach/sdmx-learning-catalogue/pull/23

Best

**Comment by OSoerensen** [comment] 2024-04-10 06:36
Looks good now, merged the request and closing this issue

**Closed as completed by OSoerensen** 2024-04-10 06:36 UTC
Labels: bug
